elf: Fix DT_* misparsing due to RVA vs raw confusion
sh_offset is a file offset, not RVA. This can cause obscure exceptions during parsing of valid ELFs:

    elftools.common.exceptions.ELFParseError: expected 2, found 0

(this "expected" is about data _length_, not value, but elftools error msg is quite obscure here).